title = "RustCon Asia 2019"
baseURL = "https://tikv.org"
languageCode = "en-us"
pygmentsCodeFences = true
pygmentsUseClasses = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
favicon = "favicon.png"
googleAnalyticsId = "TODO"

[params.dates]
start = "20 April"
end = "23 April"
year = "2019"

[params.location]
name = "TODO"
address = "TODO"

[params.description]
brief = "Beijing"
long = "Join us for the first Rust Conference in Asia!"

[params.fonts]
sansserif = "Titillium Web"
monospace = "Inconsolata"

[params.logos]
white = "img/logos/logo-white.svg"
color = "img/logos/logo-black.svg"
black = "img/logos/logo-black.svg"
pingcap = "img/logos/pingcap.png"
baidu = "img/logos/baidu.png"
nervos = "img/logos/nervos.png"

[params.assets]
fontAwesomeVersion = "5.3.1"
js  = ["jquery-3.3.1", "anchor", "app"]
css = ["syntax"]

[params.socialmedia]
github  = "https://github.com/rustcon-asia/beijing-2019"

[[params.home.buttons]]
text = "Tickets"
link = "/tickets"

[[params.home.buttons]]
text = "Call for Proposals"
link = "/cfp"

[[params.home.buttons]]
text = "Blog"
link = "/blog"


[outputs]
home = ["HTML", "REDIRECTS"]

[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"

[mediaTypes."text/netlify"]
delimiter = ""
